### PR TITLE
Fix coverage for ObjC tests

### LINKED ISSUE #369: #363 caused the coverage total to drop a lot
Now that all the ObjC code gen is done in `test/setup.dart`, these parts are not covered by tests, so the coverage total doesn't include them.

One possible fix is to restore the parts of the tests that invoked the code generator during the test.

### PR DESCRIPTION
**Pull request by liamappelbe**
Fixes #369

### CODE REVIEW

**Comment by liamappelbe** [comment]
https://coveralls.io/builds/49079929

File: test/native_objc_test/util.dart [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+import 'package:ffigen/ffigen.dart';
+import 'package:path/path.dart' as path;
+import 'package:test/test.dart';
+import 'package:yaml/yaml.dart';
+
+void generateBindingsForCoverage(String testName) {
+  // The ObjC test bindings are generated in setup.dart (see #362), which means
+  // that the ObjC related bits of ffigen are missed by test coverage. So this
+  // function just regenerates those bindings. It doesn't test anything except
```
Comment (brianquinlan) [inline test/native_objc_test/util.dart:15]: you kind of trailed off here....

File: test/native_objc_test/block_test.dart [hunk 2]
```diff
@@ -21,6 +22,7 @@ void main() {
       final dylib = File('test/native_objc_test/block_test.dylib');
       verifySetupFile(dylib);
       lib = BlockTestObjCLibrary(DynamicLibrary.open(dylib.absolute.path));
+      generateBindingsForCoverage('block');
```
Comment (brianquinlan) [inline test/native_objc_test/block_test.dart:25]: Wait...so now you are generating the bindings but not checking that they are correct?
