### PR TITLE
Fixes for typedefs

### LINKED ISSUE #71: Wrong bindings
In my case:

from
```c
typedef void (*PQnoticeProcessor) (void *arg, const char *message);

extern PQnoticeProcessor PQsetNoticeProcessor(PQnoticeProcessor proc, void *arg);
```
to
```dart
/// AUTO GENERATED FILE, DO NOT EDIT.
///
/// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class PG {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  PG(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_1>> PQsetNoticeProcessor(
    ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_2>> proc,
    ffi.Pointer<ffi.Void> arg,
  ) {
    _PQsetNoticeProcessor ??= _dylib.lookupFunction<_c_PQsetNoticeProcessor,
        _dart_PQsetNoticeProcessor>('PQsetNoticeProcessor');
    return _PQsetNoticeProcessor(
      proc,
      arg,
    );
  }

  _dart_PQsetNoticeProcessor _PQsetNoticeProcessor;
}

typedef PQnoticeProcessor_2 = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Int8>,
);

typedef _c_PQsetNoticeProcessor
    = ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_1>> Function(
  ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_2>> proc,
  ffi.Pointer<ffi.Void> arg,
);

typedef _dart_PQsetNoticeProcessor
    = ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_1>> Function(
  ffi.Pointer<ffi.NativeFunction<PQnoticeProcessor_2>> proc,
  ffi.Pointer<ffi.Void> arg,
);

```

I guess  `PQnoticeProcessor_1` and `PQnoticeProcessor_2` should be `PQnoticeProcessor`

### PR DESCRIPTION
**Pull request by mannprerak2**
closes #71 
- Fixed missing typedef used in function's return type.
- Named function typedefs are now reused.
- Added tests for typedef generation.

### CODE REVIEW

File: test/header_parser_tests/typedef.h [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file
+// for details. All rights reserved. Use of this source code is governed by a
+// BSD-style license that can be found in the LICENSE file.
+
+typedef void (*NamedFunctionProto)();
+
+struct Struct1
```
Comment (dcharkes) [inline test/header_parser_tests/typedef.h:7]: Please also add the pattern from the issue https://github.com/dart-lang/ffigen/issues/73.

```c
typedef struct _Foo {
  // ...
} Foo;
```

Comment (mannprerak2) [reply test/header_parser_tests/typedef.h:7]: The tests in `typedef.h` are only for function pointers currently, Just to check that we reuse a typedef instead of recreating it.

Comment (mannprerak2) [reply test/header_parser_tests/typedef.h:7]: #73 is related to which name we should use (from the struct namespace or `global namespace`), I will add tests for in its own PR.

Comment (dcharkes) [reply test/header_parser_tests/typedef.h:7]: 👍
