### PR TITLE
Fixed function argument - dart keyword conflict

### LINKED ISSUE #44: pub run test auto setup
We should investigate whether we can do

> Run setup to build the LLVM wrapper - pub run ffigen:setup.
> Dynamic library for some tests also need to be built before running the examples.
> cd test/native_test.
> Run dart build_test_dylib.dart.

when running `pub run test`. That might fix the Travis tests, and makes it easier for people to try out this package.

### LINKED ISSUE #47: Sanitize function argument names
Function names are sanitized to avoid conflicts with reserved Dart keywords, but function argument names are not. For example:
```c
// test.h
void var(void *in);
```
While the function is renamed to `var_1`, the conflicting `in` argument name is kept as is, which results to a parsing error:
```bash
$ dart pub run ffigen
Running in Directory: '/home/jpnurmi/Temp/test_ffigen'
  WARNING : Prefer adding Key 'name' to your config.
  WARNING : Prefer adding Key 'description' to your config.
Input Headers: [test.h]
  WARNING : Resolved name conflict: Declaration 'var' and has been renamed to 'var_1'.
  SEVERE  : Could not format because the source could not be parsed:

line 14, column 25 of test.dart: Expected an identifier.
   ╷
14 │   ffi.Pointer<ffi.Void> in,
   │                         ^^
   ╵
line 30, column 25 of test.dart: Expected an identifier.
   ╷
30 │   ffi.Pointer<ffi.Void> in,
   │                         ^^
   ╵
line 26, column 25 of test.dart: Expected an identifier.
   ╷
26 │   ffi.Pointer<ffi.Void> in,
   │                         ^^
   ╵
line 18, column 5 of test.dart: Expected an identifier.
   ╷
18 │     in,
   │     ^^
   ╵

Finished, Bindings generated in /home/jpnurmi/Temp/test_ffigen/test.dart
```
test.dart:
```dart
/// AUTO GENERATED FILE, DO NOT EDIT.
/// 
/// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class NativeLibrary{
/// Holds the Dynamic library.
final ffi.DynamicLibrary _dylib;

/// The symbols are looked up in [dynamicLibrary].
NativeLibrary(ffi.DynamicLibrary dynamicLibrary): _dylib = dynamicLibrary;

void var_1(
  ffi.Pointer<ffi.Void> in,
) {
_var_1 ??= _dylib.lookupFunction<_c_var_1,_dart_var_1>('var');
  return _var_1(
    in,
  );
}
_dart_var_1 _var_1;

}

typedef _c_var_1 = ffi.Void Function(
  ffi.Pointer<ffi.Void> in,
);

typedef _dart_var_1 = void Function(
  ffi.Pointer<ffi.Void> in,
);

```

### PR DESCRIPTION
**Pull request by mannprerak2**
Closes #47 , closes #44
- Fixed function argument name conflicts with dart keywords.
- Removed parameter names from generated typedefs
- Updated tests, examples
- Updated Travis: libclang-dev and clang are installed, `pub run ffigen:setup` is called before running tasks.

### CODE REVIEW

File: example/simple/generated_bindings.dart [hunk 1]
```diff
@@ -87,51 +87,51 @@ class NativeLibrary {
 }
 
 typedef _c_sum = ffi.Int32 Function(
-  ffi.Int32 a,
-  ffi.Int32 b,
+  ffi.Int32,
```
Comment (dcharkes) [inline example/simple/generated_bindings.dart:90]: If we ever want to make those typedefs non-private (https://github.com/dart-lang/ffigen/issues/24), the arguments having names might actually be useful.

Even for code inspection right now the names could be useful. Maybe we should keep them.

Is there a reason we're removing them?

File: lib/src/code_generator/func.dart [hunk 2]
```diff
@@ -117,7 +117,11 @@ class Func extends LookUpBinding {
     if (dartDoc != null) {
       s.write(makeDartDoc(dartDoc));
     }
-
+    // Resolve name conflicts in function parameter names.
```
Comment (dcharkes) [inline lib/src/code_generator/func.dart:120]: 5 line fix, I love it! Shows our code is written in a good way!

File: test/collision_tests/reserved_keyword_collision_test.dart [hunk 3]
```diff
@@ -24,6 +24,20 @@ void main() {
             returnType: Type.nativeType(SupportedNativeType.Void)),
         Func(
             name: 'implements',
+            parameters: [
+              Parameter(
+                type: Type.nativeType(SupportedNativeType.Int32),
+                name: 'if',
```
Comment (dcharkes) [inline test/collision_tests/reserved_keyword_collision_test.dart:30]: Please also add a test that makes a name collide after the first rename.

**Comment by dcharkes** [comment]
Please also update the changelog.

Also, update the version number in pubspec if you want me to release a version of the package with the fix.

File: example/simple/generated_bindings.dart (hunk 1 above)
Comment (mannprerak2) [reply example/simple/generated_bindings.dart:90]: No reason, I did this to not having to do conflict resolution for typedefs

File: lib/src/code_generator/func.dart (hunk 2 above)
Comment (mannprerak2) [reply lib/src/code_generator/func.dart:120]: ❣️

File: example/simple/generated_bindings.dart (hunk 1 above)
Comment (mannprerak2) [reply example/simple/generated_bindings.dart:90]: The typedefs use the same parameters so name conflict resolution will need to be updated

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,7 @@
+# 0.1.3
+- Handled function arguments - dart keyword name collision
+- Fix travis tests. Auto create dynamic library if it doesn't exist.
```
Comment (dcharkes) [inline CHANGELOG.md:3]: > Auto create dynamic library if it doesn't exist.

This you removed from the CL again?

Comment (mannprerak2) [reply CHANGELOG.md:3]: We don't create dynamic library in tests now, but manually call `pub run ffigen:setup` in travis before running tests

Comment (dcharkes) [reply CHANGELOG.md:3]: Yes, which is why the changelog should be updated.

Comment (mannprerak2) [reply CHANGELOG.md]: Yeah, done
