### PR TITLE
Fixes for `const` in name error, unnamed inline structs and empty structs.

### LINKED ISSUE #145: [Windows]`typedef const` syntax error
I'm working on Dart wrapper via `dart:ffi` for `libusb`: https://github.com/woodemi/libusb.dart

`ffigen` works greate on macOS/Linux, but the output contains some syntax error on Windows. And the output contains some wired code even though I reproduce it on an English config Windows laptop

It turns out to be some syntax error:

```dart
ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const SERVER_ROUTINE>>> DispatchTable; // 101960
ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const STUB_THUNK>>> ThunkTable; // 101966 
// ...
typedef const SERVER_ROUTINE = ... // 241521
typedef const STUB_THUNK = ... // 241524
```

Removing those `const`s resovles the problem

# Reproduce

- git clone https://github.com/woodemi/libusb
- cd libusb
- flutter pub run ffigen

# Environment

```
C:\Users\sunbr\woodemi\libusb.dart>%flutter-beta% doctor -v
[✓] Flutter (Channel unknown, 1.26.0-17.2.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-US)
    • Flutter version 1.26.0-17.2.pre at C:\Users\sunbr\flutter\flutter-1.26.x-beta
    • Framework revision 79b49b9e10 (4 days ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.53.0)
    • VS Code at C:\Users\sunbr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.63

! Doctor found issues in 2 categories.
```

# log

```
[SEVERE] : Could not format because the source could not be parsed:

line 241524, column 9 of lib\libusb.dart: Typedefs must have an explicit list of parameters.
       鈺?241524 鈹?typedef const STUB_THUNK = ffi.Void Function(
       鈹?        ^^^^^
       鈺?line 101960, column 3 of lib\libusb.dart: The name of a constructor must match the name of the enclosing class.
       鈺?101960 鈹?  ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const SERVER_ROUTINE>>> DispatchTable;
       鈹?  ^^^
       鈺?line 101966, column 3 of lib\libusb.dart: Methods must have an explicit list of parameters.
       鈺?101966 鈹?  ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const STUB_THUNK>>> ThunkTable;
       鈹?  ^^^
       鈺?line 241526, column 2 of lib\libusb.dart: A function body must be provided.
       鈺?241526 鈹?);
       鈹? ^
       鈺?line 241521, column 9 of lib\libusb.dart: Expected to find ';'.
       鈺?241521 鈹?typedef const SERVER_ROUTINE = ffi.Int64 Function(
       鈹?        ^^^^^
       鈺?line 101960, column 14 of lib\libusb.dart: Constructors can't have type parameters.
       鈺?101960 鈹?  ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const SERVER_ROUTINE>>> DispatchTable;
       鈹?             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       鈺?line 101960, column 3 of lib\libusb.dart: Methods must have an explicit list of parameters.
       鈺?101960 鈹?  ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const SERVER_ROUTINE>>> DispatchTable;
       鈹?  ^^^
       鈺?line 101966, column 3 of lib\libusb.dart: The name of a constructor must match the name of the enclosing class.
       鈺?101966 鈹?  ffi.Pointer<ffi.Pointer<ffi.NativeFunction<const STUB_THUNK>>> ThunkTable;
       鈹?  ^^^
       鈺?line 241524, column 9 of lib\libusb.dart: Expected an identifier.
       鈺?241524 鈹?typedef const STUB_THUNK = ffi.Void Function(
       鈹?        ^^^^^
       鈺?line 241521, column 36 of lib\libusb.dart: Expected to find ';'.
       鈺?241521 鈹?typedef const SERVER_ROUTINE = ffi.Int64 Function(
       鈹?                                   ^^^^^
       鈺?(13 more errors...)

Finished, Bindings generated in C:\Users\sunbr\woodemi\libusb.dart\lib\libusb.dart
```

### LINKED ISSUE #155: Null Check Exception thrown due to Nested Unnamed Structs.
In C structs can also be defined inside structs, in which case their names can be left out. Currently, we ignore generating `unnamed structs`, but for nested unnamed structs, we need to generate these structs since they are a dependency for another struct.

E.g -
```C
struct Struct3
{
    int a;

    // An unnamed struct.
    struct
    {
        int a;
        int b;
    } b;
};
```

### PR DESCRIPTION
**Pull request by mannprerak2**
Closes #145, Closes #155
- Fixed illegal use of `const` in declaration name (145).
- Fix wrong default path of `libclang.dll` in windows (Use `LLVM\bin` instead of `LLVM\lib`).
- Use `llvm` headers from `third-party/llvm/include` folder for tests instead of system installed llvm.
- Fix null check exceptions thrown due to inline unnamed struct declaration (155).
- Fix - do not allow `Opaque` members inside structs.
- Added test, updated version and changelog.

### CODE REVIEW

File: lib/src/header_parser/sub_parsers/structdecl_parser.dart [hunk 1]
```diff
@@ -130,7 +140,9 @@ void _setStructMembers(clang_types.CXCursor cursor) {
     _stack.top.struc!.members.clear();
   }
 
-  _stack.top.struc!.isInComplete = _stack.top.isInComplete;
+  // Since C can allow empty structs, We need to mark a struct incomplete if
```
Comment (dcharkes) [inline lib/src/header_parser/sub_parsers/structdecl_parser.dart:143]: C allows it, compiles it, and runs it. However, it is undefined behavior at runtime.

Maybe update the comment.

**Review by dcharkes — APPROVED** [review]

File: lib/src/header_parser/sub_parsers/structdecl_parser.dart (hunk 1 above)
Comment (mannprerak2) [reply lib/src/header_parser/sub_parsers/structdecl_parser.dart]: Updated.
Also fixed some formatting issues, which were apparently not caught by the test due to this (https://github.com/dart-lang/sdk/issues/44582)
