### PR TITLE
Use stret and fpret variants of objc_msgSend where appropriate

### LINKED ISSUE #608: Use `objc_msgSend_stret` and `objc_msgSend_fpret` instead of `objc_msgSend` for signature that require that
Repro: https://github.com/dnys1/ffigen_crash

We received a [crash report](https://github.com/aws-amplify/amplify-flutter/issues/3630) which I traced back to this code:

```dart
final screen = NSScreen.getMainScreen(lib);
screen!.visibleFrame;
//           ^ crashes on access to visibleFrame
```

The issue is not reproducible on Silicon macOS and was reported from a user with an Intel machine. I was able to reproduce it by running the repro app above under Rosetta, which I learned can be enabled in Xcode as a run destination under **Product** > **Destination** > **Destination Architectures** > **Show Both**.

Both myself and the user are running on Flutter 3.13 and Xcode `14.3.1`. This issue is reproducible on Flutter 3.10 and Flutter beta as well.

Thanks for any help!

### PR DESCRIPTION
**Pull request by liamappelbe**
Fixes #608

Also add changelog entries for #609 and #607.

### CODE REVIEW

File: lib/src/code_generator/objc_built_in_functions.dart [hunk 1]
```diff
@@ -396,3 +390,37 @@ class ObjCInternalGlobal extends LookUpBinding {
     binding?.addDependencies(dependencies);
   }
 }
+
+/// A wrapper around the objc_msgSend function, or the stret or fpret variants.
+class ObjCMsgSendFunc {
+  final bool isStret;
```
Comment (dcharkes) [inline lib/src/code_generator/objc_built_in_functions.dart:396]: Nit: It seems kind of weird we have 3 variants but then a bool.

Can we have an enum, and then use it for setting `originalName` as well?

**Review by dcharkes — APPROVED** [review]
lgtm!

Thanks @liamappelbe !
